### ISSUE TITLE
MVP 제작 TODO (4/10 ~ 4/17)

### ISSUE THREAD

**Issue by yoopark** [storyboard-lab/cerebri-class#1]
사실상 1인 개발이라 Project가 아닌 Issue로 간단히 작성합니다. 

## About Word
- [x] 해설지 따로 제작하는게 아니라 한 파일로 주는 방식으로 변경
- [x] 빠른 정답 부분 제작하기
- [ ] 해설 부분 제작하기
- [x] python-docx 다단 (break)
- [ ] find 조건 만족했을 때 볼드되도록 하는 함수
- [ ] 단복수 / 시제 변환 / 수동태 등 모듈 활용하여 함께 볼드체 / 빈칸 처리
- [ ] 중복 처리 시 무조건 해당 단어가 있는지 체크하는 것이 아니라 단복수 / 시제 변환 / 수동태까지 처리 가능하도록
- [x] python-docx 한글 폰트
- [x] python-docx heading

## About WebPage
- [x] 반드시 단어 10개 이상의 요청만 받도록
- [x] 웹디자인 시안 오면...
- [ ] 로딩 중 에러 (400, 429) 시 처리 방식 마련

**Comment by yoopark** [comment]
![image](https://user-images.githubusercontent.com/61629480/230783582-4f65e83b-3660-4c9f-a4e3-efe2e81a8695.png)
![image](https://user-images.githubusercontent.com/61629480/230783588-6f6d69ab-2cef-4e7c-8421-4dd489b2a32b.png)
![image](https://user-images.githubusercontent.com/61629480/230783605-5ab90a84-5c83-44e9-948b-ddb7f876be99.png)
